[build]
  command = "npx vue-cli-service build"
  publish = "dist/public"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["@neondatabase/serverless", "node-fetch"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[dev]
  framework = "vite"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.finnhub.io https://*.replit.app; img-src 'self' data: https:; connect-src 'self' wss: https://*.finnhub.io https://*.replit.app;"
    Cache-Control = "no-cache"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
